### ISSUE TITLE
Cena gazu w zł/kWh a nie zł/m³

### ISSUE THREAD

**Issue by matjon** [juzefwt/cieplo-wlasciwie#7]
Od 1 sierpnia 2014 PGNiG rozlicza zużycie gazu ziemnego wg kWh a nie m³:
http://www.pgnig.pl/dladomu/nowamiara
Ma to na celu ujednolicenie stawek za typy gazu takich jak E oraz L.

Tymczasem w oknie "Zmień ceny paliw i koszt pracy" ciągle podaje się cenę w m³, której nie ma już w rachunkach.

**Comment by juzefwt** [comment]
Jest już gaz przerobiony na kWh.
